배포 환경관련 Dockerfile 수정
JAVACAFE-STUDY/chainity-docker pull request #16
Opened 2019-05-11 01:45 UTC by clghks

배포 환경 변경에 따른 Dockerfile 수정 
pm2 global 삭제

2019-05-12 01:19 UTC, rygh4775 requested changes

2019-05-12 01:19 UTC, rygh4775 commented on APIServer/Dockerfile
> +RUN npm install pm2
그 전 제 질문의 의도는 pm2를 별도로 설치할 필요가 있냐는 거였는데요.
package.json에  pm2가 dependencies 목록에 이미 있어서요.

2019-05-13 15:13 UTC, clghks commented on APIServer/Dockerfile
> +RUN npm install pm2
아... 확인해보니 없어도 됩니다.

2019-05-14 00:11 UTC, rygh4775 approved these changes

2019-05-14 15:01 UTC, merged